// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaVeredas.Data;

#nullable disable

namespace SistemaVeredas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260930120000_RoturasEnVeredas")]
    partial class RoturasEnVeredas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaVeredas.Models.Paquete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Paquetes");
                });

            modelBuilder.Entity("SistemaVeredas.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("SistemaVeredas.Models.Rotura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Medidas")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<decimal>("SubtotalM2")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TipoSueloId")
                        .HasColumnType("int");

                    b.Property<int>("VeredaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoSueloId");

                    b.HasIndex("VeredaId");

                    b.ToTable("Roturas");
                });

            modelBuilder.Entity("SistemaVeredas.Models.TipoSuelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Medida")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TiposSuelo");
                });

            modelBuilder.Entity("SistemaVeredas.Models.Usuario", b =>
                {
                    b.Property<int>("UsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsId"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UsActivo")
                        .HasColumnType("bit");

                    b.Property<string>("UsApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsContrasena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("token_recovery")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsId");

                    b.HasIndex("UsEmail")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaVeredas.Models.Vereda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ACargoFrentista")
                        .HasColumnType("bit");

                    b.Property<string>("Altura")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntreCalle1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntreCalle2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("FechaReclamo")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaRelevo")
                        .HasColumnType("date");

                    b.Property<string>("Fotos")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Medicion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MedicionCordon")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("PaqueteId")
                        .HasColumnType("int");

                    b.Property<string>("Prioridad")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<bool>("TieneCordon")
                        .HasColumnType("bit");

                    b.Property<decimal?>("TotalCordonM3")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("TotalM2")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("PaqueteId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Veredas");
                });

            modelBuilder.Entity("SistemaVeredas.Models.Paquete", b =>
                {
                    b.HasOne("SistemaVeredas.Models.Proveedor", "Proveedor")
                        .WithMany("Paquetes")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("SistemaVeredas.Models.Rotura", b =>
                {
                    b.HasOne("SistemaVeredas.Models.TipoSuelo", "TipoSuelo")
                        .WithMany("Roturas")
                        .HasForeignKey("TipoSueloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaVeredas.Models.Vereda", "Vereda")
                        .WithMany("Roturas")
                        .HasForeignKey("VeredaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoSuelo");

                    b.Navigation("Vereda");
                });

            modelBuilder.Entity("SistemaVeredas.Models.Vereda", b =>
                {
                    b.HasOne("SistemaVeredas.Models.Paquete", "Paquete")
                        .WithMany("Veredas")
                        .HasForeignKey("PaqueteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaVeredas.Models.Proveedor", "Proveedor")
                        .WithMany("Veredas")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Paquete");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("SistemaVeredas.Models.Paquete", b =>
                {
                    b.Navigation("Veredas");
                });

            modelBuilder.Entity("SistemaVeredas.Models.Proveedor", b =>
                {
                    b.Navigation("Paquetes");

                    b.Navigation("Veredas");
                });

            modelBuilder.Entity("SistemaVeredas.Models.TipoSuelo", b =>
                {
                    b.Navigation("Roturas");
                });

            modelBuilder.Entity("SistemaVeredas.Models.Vereda", b =>
                {
                    b.Navigation("Roturas");
                });
#pragma warning restore 612, 618
        }
    }
}
